### ISSUE TITLE
Https and open ui > panel empty (no url)

### ISSUE THREAD

**Issue by MWDavidH** [BrowserSync/browser-sync#1152]
### Issue details

how can I have panel and https together ?

I have a problem with '--https' and ' --open ui' option

I can't have them together
### Steps to reproduce/test case

run `gulp bs`
- '--https' declared before '--open ui'
- result => I have only  `https://localhost:3000/app_dev.php/`

``` js
//== shell :: gulp bs (browsersync)
gulp.task('bs', shell.task([
    'browser-sync start --proxy \
    "https://myvhost" \
    --startPath "app_dev.php/" \
    --https \
    --open ui \
    --files "./web/css/*.css, ./web/js/*.js, app/Resources/views/**/**/**/*.html.twig"'
]));
```
- '--https' declared after '--open ui'
- result => I have only ui panel `http://localhost:3001/ and ui panel is empty 

``` js
//== shell :: gulp bs (browsersync)
gulp.task('bs', shell.task([
    'browser-sync start --proxy \
    "https://myvhost" \
    --startPath "app_dev.php/" \  
    --open ui \
    --https \
    --files "./web/css/*.css, ./web/js/*.js, app/Resources/views/**/**/**/*.html.twig"'
]));
```

![screenshot_2](https://cloud.githubusercontent.com/assets/19555404/17098655/da7e9aaa-5263-11e6-9128-68d4ded8eb5c.png)
### Please specify which version of Browsersync, node and npm you're running
- Browsersync [  2.11.1  ]
- Node        [  5.8.0  ]
- Npm         [  3.7.3  ]
### Affected platforms
- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_
### Browsersync use-case
- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI
### If CLI, please paste the entire command below

``` js

var gulp = require('gulp'), //== https://github.com/gulpjs/gulp    
    shell = require('gulp-shell'), //== https://github.com/sun-zheng-an/gulp-shell

//== shell :: gulp bs (browsersync)
gulp.task('bs', shell.task([
    'browser-sync start --proxy \
    "https://myvhost" \
    --startPath "app_dev.php/" \
    -- https \
    --open ui \
    --files "./web/css/*.css, ./web/js/*.js, app/Resources/views/**/**/**/*.html.twig"'
]));
```

**Comment by mehdivk** [comment]
Same problem here. UI doesn't honour `https` flag and tries to get data from `http`. This is the error I get in console of my UI:

`socket.js:2 GET http://localhost:2017/browser-sync/socket.io/?EIO=3&transport=polling&t=LZXWhlF`

Obviously it misses the protocol there.

**Comment by MWDavidH** [comment]
@mehdivk Hi, do you use Browser Sync CLI too ?

**Comment by mehdivk** [comment]
@MWDavidH No. I'm using it via Webpack.

**Comment by shakyShane** [comment]
Thanks all.

This was actually caused by a run-time generated file (that includes socket URLS etc) being cached by the browser. 

I've fixed it in browser-sync@2.18.3 - but you'll need to do a 'hard' reload on the UI to get the new resources, from then onwards it will not happen again. 👍

**Comment by MWDavidH** [comment]
Hi @shakyShane and thanks for this fix. 
I updated to browser-sync 2.18.5, but for me that doesn't fix the problem, 
With vhost in **https** , I have no UI panel. If i open `http://localhost:3001/`, I have an empty UI panel, so I can't use "remote debug" and others panel's options. 
Could you re open the issue ?

**Comment by shakyShane** [comment]
Did you completely clear your browser cache? Easiest way is to open dev tools, click disable cache & then reload

**Comment by MWDavidH** [comment]
Yes i clear my brwoser cache, but I use Gulp shell to open my website and the UI panel, with task `gup bs` (I describe it in the first issue post).

**Comment by MWDavidH** [comment]
@shakyShane I remember there was a Weinre console debug. I can't see it in ui panel, and can't access it with weinre default port 8080 or with url (https://192.168.1.206:8080, or http://192.168.1.206:8080). Do you know where I can find it ?.

![screenshot_1](https://cloud.githubusercontent.com/assets/19555404/21107674/d27f847a-c092-11e6-8097-b4c0d541118e.jpg)

**Comment by t-kelly** [comment]
👋 I'm experiencing the same problem with v2.24.6.

The Browsersync config is proxying an https site and I'm providing self-signed SSL cert/key. Error I'm getting in the console is:

```
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
polling-xhr.js:264 GET https://10.11.135.255:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=MLie7FQ 0 ()
```

Could this be something with Chrome blocking self-signed certs?

**Comment by enashnash** [comment]
@t-kelly Chrome was refusing my self-signed cert until I added Subject Alternative Name to the certificate so I could run somedomain.local locally.

I'm using 2.24.7 and I experience the same thing in the console with the following configuration:

```
browserSync({
  useHttps: true,
  https: {
    key: "./tools/cert/host.key",
    cert: "./tools/cert/cert.crt"
  },
  host: "somedomain.local",
  port: 3000,
  open: "external",
  ui: {
    port: 3001
  },
  server: {
    ...
  }
}
```

For me, the UI will only load over http but I can see from the console that it's requesting https. Here it is just running as localhost:

![image](https://user-images.githubusercontent.com/731351/45927756-ca1bfc80-bf2f-11e8-9f56-c6863976767b.png)

Is something up with my configuration?

**Comment by dennisbaum** [comment]
same here with bs 2.26.3, gulp, selfsigned certs and the proxy url is https: the proied site is running, but all bs-ui-pages are empty. i have emptied the cache and hard reloaded. same behavior in a fresh installed firefox.
![image](https://user-images.githubusercontent.com/562826/51091029-f7154900-1784-11e9-9485-638a69ae54c6.png)
