### ISSUE TITLE
Firefox: Connection was interrupted while the page was loading error

### ISSUE THREAD

**Issue by peteruithoven** [BrowserSync/browser-sync#697]
When I use browser-sync with Firefox I get the following error when manually refreshing the page: 
```
The connection to ws://localhost:3000/browser-sync/socket.io/?EIO=3&transport=websocket&sid=dw58x9PtxI2m3q_LAAAZ was interrupted while the page was loading.
```
This might be unavoidable Socket.io behavior but it's quite confusing when developing your own app. 
(It doesn't happen in Chrome)

**Comment by peteruithoven** [comment]
Gulpfile.js:
``` javascript
var gulp = require('gulp');
var browserSync = require('browser-sync').create();
gulp.task('server', function () {
  browserSync.init({
    server: {
      baseDir: './'
    }
  });
});

gulp.task('default', ['server']);
````
index.html:
``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>
```
package.json:
``` json
{
  "name": "browser-sync-helloworld",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "browser-sync": "^2.7.13",
    "gulp": "^3.9.0"
  }
}
```

**Comment by shinnn** [comment]
As you said, it's just a Socket.IO issue and should be fixed there. https://github.com/socketio/socket.io/issues?utf8=%E2%9C%93&q=interrupted+while+the+page+was+loading.

**Comment by trisys3** [comment]
This issue has a fix in Socket.IO, by catching the `window.onload` or `window.onbeforeunload` event. However, I am using the latest version, `2.10.0`, and it is still happening in `BrowserSync`. Is there any chance of a fix incorporating 1 or both of these 2 events?
