### ISSUE TITLE
Set-Cookie header is changed when using proxy

### ISSUE THREAD

**Issue by maciej-pawlisz** [BrowserSync/browser-sync#842]
I am using django and proxy mode in browser sync. I noticed that after using `django.contrib.messages`,  `django.contrib.sessions` stopped working (I cannot login, send post request through CSRF). This is caused by django not being able to parse message cookie, and all cookies after that. After some investigation I noticed that when django is sending:
`Set-Cookie:messages="412d773c32c6c08a1d6ddf88b24bef15a1dafd91$[[\"__json_message\"\0540\05420\054\"Cofni\\u0119to publikacj\\u0119 strony \\\"Strona G\\u0142\\u00f3wna\\\" w j\\u0119zyku Polski\"]]"; httponly; Path=/`

BrowserSync is passing:
`set-cookie:messages=412d773c32c6c08a1d6ddf88b24bef15a1dafd91$[[\"__json_message\"\0540\05420\054\"Cofni\\u0119to publikacj\\u0119 strony \\\"Strona G\\u0142\\u00f3wna\\\" w j\\u0119zyku Polski\"]]; Path=/; HttpOnly`

As you can see, there are double quotes missing around actual message. Probably django is not able to parse this cookie without them.

**Comment by jyek** [comment]
Did you resolve this? I have a similar problem.

**Comment by maciej-pawlisz** [comment]
No :( I stopped using BrowserSync because of that. The problem is with foxy
library (changing cookies https://github.com/shakyShane/foxy/issues/14) and
in python (parsing cookies: http://bugs.python.org/issue25228). I will wait
until either of them is fixed.

2015-11-12 7:58 GMT+01:00 Justin Yek <notifications@github.com>:

**Comment by reintroducing** [comment]
I'm running into a similar issue as well (all of a sudden I cant log into my Django app locally when running through the proxy) and am curious what version of OSX and browser are you running? When I try in Safari everything works as expected but OSX El Capitan 10.11.1 and Chrome 46.0.2490.80 (64-bit) is not working. 

I tried to downgrade to a prior version of foxy (11.1.2) because I thought maybe an update was made recently. When I look at foxy's release history 11.1.3 was released early August and I've killed my node_modules and reinstalled many times prior to that.  The only logical conclusion that I've come to is that either a) it's a different package that is causing this which was recently updated or b) since this started happening to me after upgrading to El Capitan I have to assume something changed and Chrome handles it differently in El Capitan because everything was working fine prior to my update two weeks or so ago.

I'm really grasping at straws here but that's all I can think of :\

**Comment by maciej-pawlisz** [comment]
I am using Windows. Maybe you upgraded your python version? I think this regression was introduced in python 2.7.9 or 2.7.10. Also Safari might auto escape cookies, so they have correct quotes even if foxy strips them.

**Comment by reintroducing** [comment]
I was on python 2.7.7 and upgraded to 2.7.10 to see if that fixed the problem :\

**Comment by reintroducing** [comment]
I just had a co-worker who has literally the same exact setup as me (down to the chrome version) run this. The only difference is that he's on Yosemite and I'm on El Capitan. His works, mine doesn't.

**Comment by reintroducing** [comment]
Sorry, I don't mean to spam this issue, but interesting read that's related here: https://github.com/rails/rails/issues/21948

**Comment by reintroducing** [comment]
For anyone following this issue here, a PR was opened against Foxy to fix this issue by a co-worker of mine. Hopefully it gets merged in shortly.

**Comment by shakyShane** [comment]
fixed in https://github.com/shakyShane/foxy/pull/16

to get the upstream changes, it's easiest to simply

```shell
npm rm browser-sync && npm i browser-sync@latest -D
```

**Comment by trey** [comment]
This is still not working for me with `grunt-browser-sync` on a Django app.

**Comment by shakyShane** [comment]
@trey can you verify your installed version of foxy by running 'npm ls foxy'

**Comment by trey** [comment]
@shakyShane this is what I get:

```
$ npm ls foxy
Example@1.0.0 /path/to/site
└─┬ browser-sync@2.10.0 extraneous
  └── foxy@11.1.4 

npm ERR! extraneous: browser-sync@2.10.0 /path/to/site/node_modules/browser-sync
npm ERR! not ok code 0
```

**Comment by shakyShane** [comment]
Remove the browser sync package with 'npm rm browser-sync' and then run the command I mentioned above but replace browser-sync with grunt-browser-sync

**Comment by trey** [comment]
Still no dice. I am getting this for `npm ls foxy`, though.

```
Example@1.0.0 /path/to/site
└─┬ grunt-browser-sync@2.2.0
  └─┬ browser-sync@2.10.0
    └── foxy@11.1.4 
```

**Comment by dokether** [comment]
For anyone running into this issue with Django, this is a deep python issue (see: http://bugs.python.org/issue25228). However, if you use DNSMasq to utilize local domains (ie. `www.mywebsite.dev`), I stopped running into this issue with BrowserSync. You can checkout https://passingcuriosity.com/2013/dnsmasq-dev-osx/ for a good tutorial on using it for OSX (and I'm sure other tutorials for *nix formats aren't heard to find).
